name: flutter_tex_js
description: A lightweight TeX plugin that uses KaTeX (JavaScript) in a native web view to render to PNG
version: 4.0.1
homepage: https://github.com/amake/flutter_tex_js

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex_js_android: ^3.0.0
  # flutter_tex_js_android:
  #   path: ../flutter_tex_js_android
  flutter_tex_js_ios: ^2.0.6
  # flutter_tex_js_ios:
  #   path: ../flutter_tex_js_ios
  flutter_tex_js_platform_interface: ^1.0.0
  # flutter_tex_js_platform_interface:
  #   path: ../flutter_tex_js_platform_interface

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_tex_js_android
      ios:
        default_package: flutter_tex_js_ios
