name: flutter_tex_js_ios
description: iOS implementation of the flutter_tex_js plugin.
version: 1.0.0
homepage: https://github.com/amake/flutter_tex_js

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tex_js_platform_interface: ^1.0.0
  # flutter_tex_js_platform_interface:
  #   path: ../flutter_tex_js_platform_interface

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_tex_js
    platforms:
      ios:
        pluginClass: FlutterTexJsPlugin
        dartPluginClass: TexRendererIOS
